import abstract_approximation_theory_approximation_normed_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace abstract_approximation_theory_approximation_normed_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end abstract_approximation_theory_approximation_normed_theorem_canonical_lane_mathlib
end HautevilleHouse
